### ISSUE TITLE
unity version?

### ISSUE THREAD

**Issue by laurentopia** [GilbertoGojira/DOTS-Sprite-Renderer#1]
the project is recognized as pre-5.0 :\
is 2019.3b8 ok?
how about additional packages required?

**Comment by GilbertoGojira** [comment]
This project requires at least Unity 2019.3.x.
Because the project is divided in several packages they all have their dependencies setup and will install the required packages upon import, but basically it requires all the DOTS packages.

**Comment by laurentopia** [comment]
what's all that stingray stuff?

**Comment by GilbertoGojira** [comment]
stingray???

**Comment by laurentopia** [comment]
![image](https://user-images.githubusercontent.com/26075468/68814517-ea27e700-062d-11ea-9154-5638cc6befda.png)
stackray

**Comment by GilbertoGojira** [comment]
Ah you are refering to Stackray stuff, those are the packages where the source of this project resides:

- Transforms . and extension and override to some systems in Unity Transforms
- Collections - an extension to Unity Collections
- Entities -  an extension to Unity Entities
- Jobs - Several generics jobs that are useful to other packages
- Mathematics - an extension to Unity Mathematics
- Sprite Renderer - a sprite renderer using DOTS
- Text - a text renderer using DOTS 

Yeah i know i should add more info in the README and i will...

**Comment by laurentopia** [comment]
No luck, what are the steps to import this example project?

**Comment by GilbertoGojira** [comment]
Just clone the repo and open the project in SpriteRendererExample with Unity 2019.3 or later.
In there there are a few example scenes but for sprites you can look specifically in scene Assets/Example/Animations

**Comment by laurentopia** [comment]
Gotcha, I had moved the example folder outside the git folder and I think unity can't find dependencies like that.
